[project]
name = "alexa-clone-for-dummies"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
  "faster-whisper",
  "groq",
  "numpy",
  "onnxruntime",
  "pillow",
  "python-dotenv",
  "sounddevice",
  "transformers",
  "torch",
  "silero-vad>=6.2.1",
  "setuptools<81",
  "resemble-perth>=1.0.1",
  "pyaudio>=0.2.14",
  "pydantic>=2.13.4",
  "chatterbox-streaming>=0.1.2",
  "ml-dtypes>=0.5",
]

[tool.pyright]
venvPath = "/workspace"
venv = ".venv"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
