[project]
name = "alexa-clone-for-dummies"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
# requires-python = ">=3.12,<3.13"
sys_platform = 'darwin'
platform_machine = 'x86_64'
dependencies = [
  "faster-whisper",
  "groq",
  "numpy",
  "onnxruntime",
  "pillow",
  "python-dotenv",
  "sounddevice",
  "transformers",
  "torch",
  "chatterbox-tts",
  "silero-vad>=6.2.1",
  "setuptools<81",
  "resemble-perth>=1.0.1",
  "pyaudio>=0.2.14",
]

[tool.pyright]
venvPath = "/workspace"
venv = ".venv"
